<head>

</head>

<!-- <h1>InterestPoint - Login</h1> -->

<br>
<p>Please Log in with your username and password below.</p>

<form action ="?" method="POST" class="center">
    <label for="username">Username:</label><br />
    <input type="text" name="username" id="username" maxlength="30" size="20"/><br />
    <label for="password">Password:</label><br />
    <input type="password" name="password" id="password" maxlength="30" size="20" /><br />
    <br />
    <input class="button" type="submit" />

</form>

<h2>New User?</h2>
<p><a href="signup.php">Sign Up Here</a> </p>